-- مركز السيارة | Supabase production foundation
-- Run this migration in a dedicated Supabase project for this store.
create extension if not exists pgcrypto;

create type public.user_role as enum ('customer','admin');
create type public.order_status as enum ('pending','confirmed','processing','shipped','delivered','cancelled');
create type public.payment_method as enum ('cod','bank_transfer');
create type public.payment_status as enum ('pending','paid','failed','refunded');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text unique,
  role public.user_role not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  is_active boolean not null default true,
  sort_order int not null default 0
);

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  is_active boolean not null default true
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  category_id bigint references public.categories(id) on delete set null,
  brand_id bigint references public.brands(id) on delete set null,
  name text not null,
  slug text not null unique,
  sku text unique,
  description text,
  price_iqd bigint not null check (price_iqd >= 0),
  compare_at_iqd bigint check (compare_at_iqd is null or compare_at_iqd >= price_iqd),
  stock_qty int not null default 0 check (stock_qty >= 0),
  low_stock_threshold int not null default 5,
  is_active boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  storage_path text not null,
  alt_text text,
  sort_order int not null default 0
);

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  make text not null,
  model text not null,
  year_from int,
  year_to int,
  engine text,
  unique(make, model, year_from, year_to, engine)
);

create table if not exists public.product_compatibility (
  product_id uuid not null references public.products(id) on delete cascade,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  notes text,
  primary key(product_id, vehicle_id)
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade,
  full_name text not null,
  phone text not null,
  governorate text not null,
  area text not null,
  address_line text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.shipping_rates (
  governorate text primary key,
  fee_iqd bigint not null check (fee_iqd >= 0),
  active boolean not null default true
);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  discount_percent numeric(5,2) check (discount_percent between 0 and 100),
  discount_iqd bigint check (discount_iqd is null or discount_iqd >= 0),
  min_order_iqd bigint not null default 0,
  max_uses int,
  used_count int not null default 0,
  starts_at timestamptz,
  expires_at timestamptz,
  active boolean not null default true
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  user_id uuid references public.profiles(id) on delete set null,
  customer_name text not null,
  phone text not null,
  governorate text not null,
  area text not null,
  address_line text not null,
  subtotal_iqd bigint not null check (subtotal_iqd >= 0),
  shipping_iqd bigint not null default 0 check (shipping_iqd >= 0),
  discount_iqd bigint not null default 0 check (discount_iqd >= 0),
  total_iqd bigint not null check (total_iqd >= 0),
  payment_method public.payment_method not null default 'cod',
  payment_status public.payment_status not null default 'pending',
  status public.order_status not null default 'pending',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  sku text,
  unit_price_iqd bigint not null check (unit_price_iqd >= 0),
  quantity int not null check (quantity > 0),
  line_total_iqd bigint not null check (line_total_iqd >= 0)
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id, product_id)
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating int not null check (rating between 1 and 5),
  title text,
  body text,
  approved boolean not null default false,
  created_at timestamptz not null default now(),
  unique(product_id,user_id)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_brand_idx on public.products(brand_id);
create index if not exists products_active_idx on public.products(is_active, featured);
create index if not exists orders_user_idx on public.orders(user_id, created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists compatibility_vehicle_idx on public.product_compatibility(vehicle_id);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.brands enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.vehicles enable row level security;
alter table public.product_compatibility enable row level security;
alter table public.addresses enable row level security;
alter table public.shipping_rates enable row level security;
alter table public.coupons enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.favorites enable row level security;
alter table public.reviews enable row level security;
alter table public.audit_logs enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create policy "public active categories" on public.categories for select using (is_active = true);
create policy "public active brands" on public.brands for select using (is_active = true);
create policy "public active products" on public.products for select using (is_active = true);
create policy "public product images" on public.product_images for select using (true);
create policy "public vehicles" on public.vehicles for select using (true);
create policy "public compatibility" on public.product_compatibility for select using (true);
create policy "public shipping rates" on public.shipping_rates for select using (active = true);
create policy "public approved reviews" on public.reviews for select using (approved = true);

create policy "own profile read" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "own profile update" on public.profiles for update using (id = auth.uid() or public.is_admin());
create policy "own addresses" on public.addresses for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy "own orders read" on public.orders for select using (user_id = auth.uid() or public.is_admin());
create policy "own order items read" on public.order_items for select using (exists(select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.is_admin())));
create policy "own favorites" on public.favorites for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own reviews" on public.reviews for insert with check (user_id = auth.uid());

create policy "admin categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy "admin brands" on public.brands for all using (public.is_admin()) with check (public.is_admin());
create policy "admin products" on public.products for all using (public.is_admin()) with check (public.is_admin());
create policy "admin images" on public.product_images for all using (public.is_admin()) with check (public.is_admin());
create policy "admin vehicles" on public.vehicles for all using (public.is_admin()) with check (public.is_admin());
create policy "admin compatibility" on public.product_compatibility for all using (public.is_admin()) with check (public.is_admin());
create policy "admin shipping" on public.shipping_rates for all using (public.is_admin()) with check (public.is_admin());
create policy "admin coupons" on public.coupons for all using (public.is_admin()) with check (public.is_admin());
create policy "admin orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());
create policy "admin order items" on public.order_items for all using (public.is_admin()) with check (public.is_admin());
create policy "admin reviews" on public.reviews for all using (public.is_admin()) with check (public.is_admin());
create policy "admin audit" on public.audit_logs for all using (public.is_admin()) with check (public.is_admin());

insert into public.categories(name,slug,sort_order) values
('قطع غيار','spare-parts',1),('زيوت','oils',2),('إكسسوارات','accessories',3),('كهربائيات','electrical',4),('أدوات','tools',5)
on conflict (slug) do nothing;

insert into public.shipping_rates(governorate,fee_iqd) values
('بغداد',5000),('البصرة',10000),('أربيل',10000),('النجف',8000),('كربلاء',8000),('نينوى',10000),('ذي قار',10000),('الأنبار',10000),('ديالى',8000),('واسط',8000),('بابل',7000),('القادسية',8000),('ميسان',10000),('المثنى',10000),('صلاح الدين',10000),('كركوك',10000),('دهوك',12000),('السليمانية',12000)
on conflict (governorate) do nothing;

-- IMPORTANT: create the first admin manually after creating its auth user:
-- update public.profiles set role = 'admin' where id = '<AUTH_USER_UUID>';
