const C=window.STORE_CONFIG||{};let db=null,session=null;
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('ar-IQ').format(n)+' د.ع';
function msg(t){$('#loginMsg').textContent=t}
async function boot(){if(!C.supabaseUrl||!C.supabaseAnonKey||!window.supabase){msg('ضع بيانات Supabase في config.js أولاً.');return}db=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);const s=await db.auth.getSession();session=s.data.session;if(session)await verify();else $('#loginBox').hidden=false}
async function verify(){const {data,error}=await db.from('profiles').select('role').eq('id',session.user.id).single();if(error||data?.role!=='admin'){await db.auth.signOut();session=null;$('#loginBox').hidden=false;msg('هذا الحساب ليس لديه صلاحية admin.');return}$('#loginBox').hidden=true;$('#dashboard').hidden=false;await load()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!db)return;const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)return msg(error.message);const s=await db.auth.getSession();session=s.data.session;await verify()};
$('#logout').onclick=async()=>{await db?.auth.signOut();location.reload()};$('#refresh').onclick=load;
async function load(){if(!db)return;const [{data:orders},{data:products}]=await Promise.all([db.from('orders').select('*').order('created_at',{ascending:false}).limit(50),db.from('products').select('*').order('created_at',{ascending:false})]);const os=orders||[],ps=products||[];$('#kOrders').textContent=os.length;$('#kSales').textContent=money(os.filter(o=>o.status!=='cancelled').reduce((n,o)=>n+o.total_iqd,0));$('#kProducts').textContent=ps.length;$('#kLow').textContent=ps.filter(p=>p.stock_qty<=p.low_stock_threshold).length;$('#ordersTable').innerHTML=os.length?`<table><thead><tr><th>الطلب</th><th>العميل</th><th>الإجمالي</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>${os.map(o=>`<tr><td>${o.order_number}</td><td>${o.customer_name}<br>${o.phone}</td><td>${money(o.total_iqd)}</td><td><select data-status="${o.id}">${['pending','confirmed','processing','shipped','delivered','cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td><td>${new Date(o.created_at).toLocaleString('ar-IQ')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">لا توجد طلبات.</div>';$('[data-status]')?.parentElement?.parentElement;document.querySelectorAll('[data-status]').forEach(el=>el.onchange=async()=>{await db.from('orders').update({status:el.value,updated_at:new Date().toISOString()}).eq('id',el.dataset.status);load()});$('#productsTable').innerHTML=ps.length?`<table><thead><tr><th>SKU</th><th>المنتج</th><th>السعر</th><th>المخزون</th><th>حالة</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${p.sku||'—'}</td><td>${p.name}</td><td>${money(p.price_iqd)}</td><td><input class="stock-input" data-stock="${p.id}" value="${p.stock_qty}" type="number" min="0"></td><td>${p.is_active?'نشط':'مخفي'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">لا توجد منتجات.</div>';document.querySelectorAll('[data-stock]').forEach(el=>el.onchange=async()=>{await db.from('products').update({stock_qty:Number(el.value),updated_at:new Date().toISOString()}).eq('id',el.dataset.stock)})}
$('#addProduct').onclick=async()=>{if(!db)return;const name=prompt('اسم المنتج');if(!name)return;const price=Number(prompt('السعر بالدينار')||0);const sku=prompt('SKU اختياري')||`SKU-${Date.now()}`;const slug=sku.toLowerCase().replace(/[^a-z0-9-]/g,'-');const {error}=await db.from('products').insert({name,slug,sku,price_iqd:price,stock_qty:0,is_active:true});if(error)alert(error.message);else load()};
boot();