const C=window.STORE_CONFIG||{shipping:{},currency:'د.ع'};
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('ar-IQ').format(Number(n)||0)+' '+(C.currency||'د.ع');
const PRODUCTS=[
{id:'1',name:'فحمات فرامل أمامية أصلية',cat:'قطع غيار',price:45000,old:50000,rating:4.9,stock:12,brand:'OEM',icon:'🛞',badge:'الأكثر مبيعاً',fit:['Toyota','Hyundai','Kia']},
{id:'2',name:'فلتر زيت Premium للمحركات',cat:'زيوت',price:12000,old:15000,rating:4.8,stock:35,brand:'Premium',icon:'🔩',badge:'عرض',fit:['Toyota','Hyundai','Kia','Nissan']},
{id:'3',name:'زيت محرك 5W-30 تخليقي',cat:'زيوت',price:38000,old:45000,rating:4.9,stock:20,brand:'Ultra',icon:'🛢️',badge:'خصم',fit:['Universal']},
{id:'4',name:'شاحن سيارة سريع USB-C 45W',cat:'كهربائيات',price:18000,old:22000,rating:4.7,stock:50,brand:'Volt',icon:'🔌',badge:'جديد',fit:['Universal']},
{id:'5',name:'كمبروسر هواء رقمي',cat:'أدوات',price:32000,old:36000,rating:4.8,stock:8,brand:'ProTool',icon:'💨',badge:'مميز',fit:['Universal']},
{id:'6',name:'دعاسات سيارة جلدية فاخرة',cat:'إكسسوارات',price:65000,old:75000,rating:4.9,stock:6,brand:'Lux',icon:'🚘',badge:'جديد',fit:['Toyota','Hyundai','Kia']},
{id:'7',name:'جهاز فحص OBD2 ذكي',cat:'أدوات',price:42000,old:49000,rating:4.8,stock:14,brand:'ScanPro',icon:'📟',badge:'الأكثر طلباً',fit:['Universal']},
{id:'8',name:'لمبات LED للسيارة H7',cat:'كهربائيات',price:28000,old:34000,rating:4.7,stock:25,brand:'Bright',icon:'💡',badge:'عرض',fit:['Universal']}
];
const GOV=C.shipping||{};
let activeCat='all',sort='featured';
let cart=JSON.parse(localStorage.getItem('al3ab-cart')||'[]');
let favs=JSON.parse(localStorage.getItem('al3ab-favorites')||'[]');
let orders=JSON.parse(localStorage.getItem('al3ab-orders')||'[]');
const get=id=>PRODUCTS.find(p=>String(p.id)===String(id));
function persist(){localStorage.setItem('al3ab-cart',JSON.stringify(cart));localStorage.setItem('al3ab-favorites',JSON.stringify(favs));localStorage.setItem('al3ab-orders',JSON.stringify(orders));}
function subtotal(){return cart.reduce((t,x)=>t+(get(x.id)?.price||0)*x.qty,0)}
function renderProducts(){
 const input=$('#searchInput');const grid=$('#productGrid');if(!input||!grid)return;
 const q=(input.value||'').trim().toLowerCase();let list=PRODUCTS.filter(p=>(activeCat==='all'||p.cat===activeCat)&&(!q||`${p.name} ${p.cat} ${p.brand}`.toLowerCase().includes(q)));
 if(sort==='low')list=[...list].sort((a,b)=>a.price-b.price);if(sort==='high')list=[...list].sort((a,b)=>b.price-a.price);if(sort==='rating')list=[...list].sort((a,b)=>b.rating-a.rating);
 grid.innerHTML=list.length?list.map(p=>`<article class="product" data-product="${p.id}"><div class="product-img"><span class="badge">${p.badge}</span><button class="fav ${favs.includes(p.id)?'active':''}" data-fav="${p.id}" aria-label="المفضلة">${favs.includes(p.id)?'♥':'♡'}</button><span>${p.icon}</span></div><div class="product-body"><div class="product-cat">${p.cat} · ${p.brand}</div><h3>${p.name}</h3><div class="stars">★★★★★ <span>(${p.rating})</span></div><div class="stock ${p.stock<10?'low':''}">${p.stock<10?`متبقي ${p.stock} فقط`:'متوفر بالمخزن'}</div><div class="price">${money(p.price)} ${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><button class="add" data-add="${p.id}">أضف للسلة +</button></div></article>`).join(''):'<div class="empty" style="grid-column:1/-1">🔎<b>ما لقينا منتجات مطابقة</b><span>جرّب اسم القطعة أو الفئة أو الماركة.</span></div>';
}
function renderCart(){
 const count=$('#cartCount'),total=$('#cartTotal'),items=$('#cartItems');if(!count||!total||!items)return;
 count.textContent=cart.reduce((n,x)=>n+x.qty,0);total.textContent=money(subtotal());
 items.innerHTML=cart.length?cart.map(x=>{const p=get(x.id);return p?`<div class="cart-row"><div class="cart-thumb">${p.icon}</div><div><h4>${p.name}</h4><small>${money(p.price)}</small><div class="qty"><button data-minus="${p.id}">−</button><b>${x.qty}</b><button data-plus="${p.id}">+</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`:''}).join(''):'<div class="empty">🛒<b>السلة فارغة</b><span>أضف المنتجات وتابع الطلب.</span></div>';
}
function openCart(){ $('#cartDrawer')?.classList.add('open');$('#overlay')?.classList.add('open'); }
function closeCart(){ $('#cartDrawer')?.classList.remove('open');$('#overlay')?.classList.remove('open'); }
function add(id){const p=get(id);if(!p||p.stock<1)return;const x=cart.find(i=>i.id===p.id);if(x)x.qty=Math.min(x.qty+1,p.stock);else cart.push({id:p.id,qty:1});persist();renderCart();openCart();}
function qty(id,d){const x=cart.find(i=>i.id===String(id));if(!x)return;x.qty+=d;const p=get(id);if(p)x.qty=Math.min(x.qty,p.stock);if(x.qty<1)cart=cart.filter(i=>i.id!==String(id));persist();renderCart();}
function modal(html){const box=$('#modalContent'),m=$('#modal');if(!box||!m)return;box.innerHTML=html;m.classList.add('open');}
function closeModal(){$('#modal')?.classList.remove('open');}
function filterCategory(c){activeCat=c;renderProducts();document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'});$('#categories')?.classList.remove('open');}
function fitment(){modal(`<button class="close-modal" onclick="closeModal()">×</button><h2>اختار حسب سيارتك 🚗</h2><p class="muted">خلينا نضيق النتائج قبل ما تشتري.</p><form class="checkout-form" id="fitForm"><div class="form-row"><select id="fitMake" required><option value="">الماركة</option><option>Toyota</option><option>Hyundai</option><option>Kia</option><option>Nissan</option></select><input id="fitModel" required placeholder="الموديل"></div><div class="form-row"><input id="fitYear" type="number" min="1980" max="2035" placeholder="السنة"><select id="fitCat" required><option value="">نوع القطعة</option>${['قطع غيار','زيوت','إكسسوارات','كهربائيات','أدوات'].map(x=>`<option>${x}</option>`).join('')}</select></div><button class="btn-primary full">عرض القطع المناسبة</button></form>`);$('#fitForm').onsubmit=e=>{e.preventDefault();const make=$('#fitMake').value,cat=$('#fitCat').value;activeCat=cat;renderProducts();closeModal();document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'});setTimeout(()=>modal(`<button class="close-modal" onclick="closeModal()">×</button><h2>نتيجة البحث</h2><p class="muted">عرضنا فئة <b>${cat}</b> مع المنتجات العامة والمتوافقة مبدئياً مع <b>${make}</b>. للمطابقة الدقيقة نحتاج بيانات المركبة في قاعدة البيانات.</p><button class="btn-primary full" onclick="closeModal()">تصفح النتائج</button>`),180);};}
function showOrders(){modal(`<button class="close-modal" onclick="closeModal()">×</button><h2>طلباتي 📦</h2>${orders.length?orders.map(o=>`<div class="order-card"><b>${o.no}</b><span>${o.status}</span><strong>${money(o.total)}</strong><small>${new Date(o.date).toLocaleString('ar-IQ')}</small></div>`).join(''):'<div class="empty">لا توجد طلبات بعد.</div>'}`);}
function showFavorites(){const ps=favs.map(get).filter(Boolean);modal(`<button class="close-modal" onclick="closeModal()">×</button><h2>المفضلة ❤️</h2>${ps.length?ps.map(p=>`<div class="order-card"><span>${p.icon} ${p.name}</span><strong>${money(p.price)}</strong></div>`).join(''):'<div class="empty">المفضلة فارغة.</div>'}`);}
function track(){modal(`<button class="close-modal" onclick="closeModal()">×</button><h2>تتبع الطلب 📦</h2><form class="checkout-form" id="trackForm"><input id="trackNo" required placeholder="CAR-12345678"><button class="btn-primary full">بحث</button></form><div id="trackResult"></div>`);$('#trackForm').onsubmit=e=>{e.preventDefault();const o=orders.find(x=>x.no===($('#trackNo').value||'').trim());$('#trackResult').innerHTML=o?`<div class="order-card"><b>${o.no}</b><span>${o.status}</span><strong>${money(o.total)}</strong></div>`:'<div class="empty">ما لقينا هذا الطلب.</div>';};}
function info(t,b){modal(`<button class="close-modal" onclick="closeModal()">×</button><h2>${t}</h2><p class="info-text">${b}</p>`);}
function account(){modal(`<button class="close-modal" onclick="closeModal()">×</button><h2>حسابي 👤</h2><p class="muted">واجهة الحساب جاهزة، وربط Supabase يتفعل عند وضع بيانات المشروع.</p><button class="btn-primary full" onclick="showOrders()">طلباتي (${orders.length})</button>`);}
function checkout(){
 if(!cart.length)return modal('<button class="close-modal" onclick="closeModal()">×</button><h2>السلة فارغة</h2>');
 const sub=subtotal();
 modal(`<button class="close-modal" onclick="closeModal()">×</button><h2>إتمام الطلب</h2><div class="order-summary"><span>المنتجات</span><b>${money(sub)}</b></div><form class="checkout-form" id="orderForm"><div class="form-row"><input id="nm" required placeholder="الاسم الكامل"><input id="ph" required inputmode="tel" placeholder="رقم الهاتف 07XXXXXXXXX"></div><div class="form-row"><select id="gov" required><option value="">المحافظة</option>${Object.keys(GOV).map(g=>`<option value="${g}">${g.replace('_',' ')}</option>`).join('')}</select><input id="area" required placeholder="المنطقة / القضاء"></div><textarea id="addr" rows="3" required placeholder="العنوان بالتفصيل وأقرب نقطة دالة"></textarea><select id="pay"><option>الدفع عند الاستلام</option><option>تحويل إلكتروني</option></select><div class="shipping-line"><span>الشحن</span><b id="sf">اختر المحافظة</b></div><div class="shipping-line total"><span>الإجمالي</span><b id="ft">${money(sub)}</b></div><button class="btn-primary full">تأكيد الطلب</button></form>`);
 $('#gov').onchange=()=>{const fee=Number(GOV[$('#gov').value]||0);$('#sf').textContent=money(fee);$('#ft').textContent=money(sub+fee);};
 $('#orderForm').onsubmit=e=>{e.preventDefault();const ph=($('#ph').value||'').replace(/\s/g,'');if(!/^07\d{9}$/.test(ph))return alert('رقم الهاتف يجب أن يبدأ بـ 07 ويتكون من 11 رقم');const shipping=Number(GOV[$('#gov').value]||0),no='CAR-'+Date.now().toString().slice(-8),o={no,date:new Date().toISOString(),name:$('#nm').value,phone:ph,governorate:$('#gov').value,area:$('#area').value,address:$('#addr').value,payment:$('#pay').value,total:sub+shipping,status:'قيد المراجعة',items:[...cart]};orders.unshift(o);cart=[];persist();renderCart();closeModal();modal(`<button class="close-modal" onclick="closeModal()">×</button><div class="success-box"><div>✅</div><h2>تم استلام طلبك</h2><p>رقم الطلب <b>${no}</b></p><p>الإجمالي <b>${money(o.total)}</b></p><button class="btn-primary" onclick="closeModal();showOrders()">عرض الطلب</button></div>`);};
}
function init(){
 $('#searchInput')?.addEventListener('input',renderProducts);$('#searchBtn')?.addEventListener('click',()=>{renderProducts();document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'});});$('#sortSelect')?.addEventListener('change',e=>{sort=e.target.value;renderProducts();});$('#allProducts')?.addEventListener('click',()=>filterCategory('all'));$('#offersBtn')?.addEventListener('click',()=>filterCategory('زيوت'));$('#cartBtn')?.addEventListener('click',openCart);$('#closeCart')?.addEventListener('click',closeCart);$('#overlay')?.addEventListener('click',closeCart);$('#checkoutBtn')?.addEventListener('click',checkout);$('#accountBtn')?.addEventListener('click',account);$('#footerAccount')?.addEventListener('click',e=>{e.preventDefault();account()});$('#ordersLink')?.addEventListener('click',e=>{e.preventDefault();showOrders()});$('#favoritesLink')?.addEventListener('click',e=>{e.preventDefault();showFavorites()});$('#trackOrderLink')?.addEventListener('click',e=>{e.preventDefault();track()});$('#trackTool')?.addEventListener('click',track);$('#returnsLink')?.addEventListener('click',e=>{e.preventDefault();info('الاستبدال والاسترجاع','للطلبات التي لم تُستخدم أو تتضرر أثناء التوصيل تواصل مع الدعم مع رقم الطلب.')});$('#contactLink')?.addEventListener('click',e=>{e.preventDefault();info('تواصل معنا','خدمة العملاء: 0770 000 0000 — سيتم إضافة واتساب والبريد عند ربطه.')});$('#fitmentBtn')?.addEventListener('click',fitment);$('#toolFitment')?.addEventListener('click',fitment);$('#mobileMenu')?.addEventListener('click',()=>$('#categories')?.classList.toggle('open'));$('#modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
 document.addEventListener('click',e=>{const cat=e.target.closest('[data-cat]');if(cat){e.preventDefault();filterCategory(cat.dataset.cat);}const addBtn=e.target.closest('[data-add]');if(addBtn){e.preventDefault();add(addBtn.dataset.add);}const fav=e.target.closest('[data-fav]');if(fav){const id=String(fav.dataset.fav);favs=favs.includes(id)?favs.filter(x=>x!==id):[...favs,id];persist();renderProducts();}const minus=e.target.closest('[data-minus]');if(minus)qty(minus.dataset.minus,-1);const plus=e.target.closest('[data-plus]');if(plus)qty(plus.dataset.plus,1);const product=e.target.closest('[data-product]');if(product&&!e.target.closest('button')){const p=get(product.dataset.product);if(p)modal(`<button class="close-modal" onclick="closeModal()">×</button><div class="detail-art">${p.icon}</div><span class="eyebrow">${p.cat} · ${p.brand}</span><h2>${p.name}</h2><div class="stars">★★★★★ <span>${p.rating}/5</span></div><div class="price">${money(p.price)}</div><p class="muted">متوفر حالياً: ${p.stock}. تأكد من توافق القطعة مع سيارتك قبل الطلب.</p><div style="display:flex;gap:8px"><button class="btn-primary" onclick="add('${p.id}');closeModal()">أضف للسلة</button><button class="btn-secondary" onclick="closeModal()">إغلاق</button></div>`);}});
 renderProducts();renderCart();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();