const C=window.STORE_CONFIG||{shipping:{},currency:'د.ع'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const num=n=>new Intl.NumberFormat('en-US').format(Number(n)||0),money=n=>`${num(n)} ${C.currency||'د.ع'}`;
const IMG='https://images.unsplash.com/photo-';
const PRODUCTS=[
{id:'1',name:'فحمات فرامل أمامية أصلية',cat:'قطع غيار',sub:'فرامل',price:45000,old:50000,rating:4.9,stock:12,brand:'OEM',badge:'الأكثر مبيعاً',image:'https://cdn.awsli.com.br/2500x2500/2695/2695989/produto/263323770250568791e.jpg',fit:['Toyota','Hyundai','Kia']},
{id:'2',name:'فلتر زيت Premium للمحركات',cat:'زيوت',sub:'فلاتر',price:12000,old:15000,rating:4.8,stock:35,brand:'Premium',badge:'عرض',image:'https://cdn.autodoc.de/thumb?id=11156535&lng=en&m=0&n=0&rev=94078092',fit:['Toyota','Hyundai','Kia','Nissan']},
{id:'3',name:'زيت محرك 5W-30 تخليقي',cat:'زيوت',sub:'زيوت محرك',price:38000,old:45000,rating:4.9,stock:20,brand:'Ultra',badge:'خصم',image:'https://cdn.autodoc.de/thumb?id=27306321&lng=pt&m=0&n=0&rev=94078027',fit:['Toyota','Hyundai','Kia','Nissan']},
{id:'4',name:'شاحن سيارة سريع USB-C 45W',cat:'كهربائيات',sub:'شحن',price:18000,old:22000,rating:4.7,stock:50,brand:'Volt',badge:'جديد',image:'https://us.ugreen.com/cdn/shop/products/ugreen-130w-usb-c-car-charger-219754.png?v=1764234772&width=1600',fit:['Universal']},
{id:'5',name:'كمبروسر هواء رقمي',cat:'أدوات',sub:'نفخ',price:32000,old:36000,rating:4.8,stock:8,brand:'ProTool',badge:'مميز',image:'https://ueeshop.ly200-cdn.com/u_file/UPBB/UPBB682/2412/11/products/CAP032-1.jpg',fit:['Universal']},
{id:'6',name:'دعاسات سيارة جلدية فاخرة',cat:'إكسسوارات',sub:'داخلية',price:65000,old:75000,rating:4.9,stock:6,brand:'Lux',badge:'جديد',image:'https://m.media-amazon.com/images/I/71tAwSrkwfL.jpg',fit:['Toyota','Hyundai','Kia']},
{id:'7',name:'جهاز فحص OBD2 ذكي',cat:'أدوات',sub:'فحص',price:42000,old:49000,rating:4.8,stock:14,brand:'ScanPro',badge:'الأكثر طلباً',image:'https://m.media-amazon.com/images/I/41XfoPw9V6L.jpg',fit:['Universal']},
{id:'8',name:'لمبات LED للسيارة H7',cat:'كهربائيات',sub:'إنارة',price:28000,old:34000,rating:4.7,stock:25,brand:'Bright',badge:'عرض',image:'https://mircaraudio.com/media/store/image0_111267.png',fit:['Universal']},
{id:'9',name:'ماء رديتر أحمر Long Life 5L',cat:'زيوت',sub:'تبريد',price:16500,old:19000,rating:4.8,stock:18,brand:'CoolMax',badge:'موصى به',image:'https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'10',name:'شمعات احتراق Iridium',cat:'قطع غيار',sub:'محرك',price:36000,old:42000,rating:4.9,stock:22,brand:'NGK',badge:'جديد',image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=82',fit:['Toyota','Hyundai','Kia','Nissan']},
{id:'11',name:'مساحات زجاج أمامي Silicone',cat:'إكسسوارات',sub:'خارجية',price:19000,old:23000,rating:4.7,stock:31,brand:'ClearView',badge:'عرض',image:'https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'12',name:'كابل بطارية Heavy Duty',cat:'كهربائيات',sub:'بطارية',price:14500,old:17000,rating:4.8,stock:15,brand:'PowerLine',badge:'عملي',image:'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'13',name:'عدة مفاتيح Ratchet 46 قطعة',cat:'أدوات',sub:'عدة',price:55000,old:65000,rating:4.9,stock:9,brand:'ToolPro',badge:'مميز',image:'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'14',name:'منظف بخاخ نظام الوقود',cat:'قطع غيار',sub:'صيانة',price:11000,old:14000,rating:4.6,stock:42,brand:'FuelCare',badge:'اقتصادي',image:'https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=901&q=80',fit:['Universal']},
{id:'15',name:'حامل هاتف مغناطيسي للسيارة',cat:'إكسسوارات',sub:'داخلية',price:12500,old:15000,rating:4.7,stock:60,brand:'DriveFix',badge:'الأكثر طلباً',image:'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'16',name:'كفر مقود جلد أسود فاخر',cat:'إكسسوارات',sub:'داخلية',price:22000,old:26000,rating:4.8,stock:17,brand:'Lux',badge:'جديد',image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'17',name:'فلتر هواء للمحرك',cat:'زيوت',sub:'فلاتر',price:13500,old:16000,rating:4.8,stock:27,brand:'AirFlow',badge:'عرض',image:'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=82',fit:['Toyota','Hyundai','Kia']},
{id:'18',name:'مضخة غسيل سيارات محمولة',cat:'أدوات',sub:'تنظيف',price:72000,old:85000,rating:4.7,stock:7,brand:'WashPro',badge:'مميز',image:'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'19',name:'مصابيح LED داخلية 12V',cat:'كهربائيات',sub:'إنارة',price:9000,old:11000,rating:4.6,stock:80,brand:'Bright',badge:'اقتصادي',image:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'20',name:'مضاد صدأ وحماية أسفل السيارة',cat:'قطع غيار',sub:'حماية',price:17500,old:21000,rating:4.7,stock:24,brand:'Shield',badge:'موصى به',image:'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'21',name:'منظم ضغط إطارات رقمي',cat:'أدوات',sub:'إطارات',price:23500,old:28000,rating:4.8,stock:19,brand:'AirCheck',badge:'جديد',image:'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=900&q=82',fit:['Universal']},
{id:'22',name:'ستارة شمس أمامية Premium',cat:'إكسسوارات',sub:'خارجية',price:15500,old:19000,rating:4.5,stock:28,brand:'SunGuard',badge:'عرض',image:'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=901&q=80',fit:['Universal']},
{id:'23',name:'سائل فرامل DOT4 500ml',cat:'زيوت',sub:'فرامل',price:8500,old:10000,rating:4.8,stock:39,brand:'BrakeSafe',badge:'أساسي',image:'https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=902&q=80',fit:['Universal']},
{id:'24',name:'مقياس فولت وبطارية 12V',cat:'كهربائيات',sub:'فحص',price:14000,old:17500,rating:4.7,stock:33,brand:'VoltCheck',badge:'عملي',image:'https://images.unsplash.com/photo-1530046339913-e3c2d0c3f77e?auto=format&fit=crop&w=900&q=82',fit:['Universal']}
];
const GOV=C.shipping||{};
let activeCat='all',sort='featured',query='',minPrice='',maxPrice='',minRating=0,visibleLimit=9;
let cart=JSON.parse(localStorage.getItem('al3ab-cart')||'[]');
let favs=JSON.parse(localStorage.getItem('al3ab-favorites')||'[]').map(String);
let orders=JSON.parse(localStorage.getItem('al3ab-orders')||'[]');
let viewed=JSON.parse(localStorage.getItem('al3ab-viewed')||'[]').map(String);
const get=id=>PRODUCTS.find(p=>String(p.id)===String(id));
const esc=s=>String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const img=(p,cls='')=>`<img class="${cls}" src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.hidden=false"><span class="image-fallback" hidden>الصورة غير متاحة</span>`;
function persist(){localStorage.setItem('al3ab-cart',JSON.stringify(cart));localStorage.setItem('al3ab-favorites',JSON.stringify(favs));localStorage.setItem('al3ab-orders',JSON.stringify(orders));localStorage.setItem('al3ab-viewed',JSON.stringify(viewed));}
function subtotal(){return cart.reduce((t,x)=>t+(get(x.id)?.price||0)*x.qty,0)}
function toast(message,ok=true){const s=$('#toastStack');if(!s)return;const t=document.createElement('div');t.className=`toast ${ok?'success-toast':''}`;t.innerHTML=`<span class="toast-icon">${ok?'✓':'!'}</span><span>${esc(message)}</span>`;s.appendChild(t);setTimeout(()=>t.remove(),3000)}
function filterList(){let list=PRODUCTS.filter(p=>{const text=`${p.name} ${p.cat} ${p.sub} ${p.brand}`.toLowerCase();const q=query.toLowerCase();return(activeCat==='all'||p.cat===activeCat)&&(!q||text.includes(q))&&(!minPrice||p.price>=Number(minPrice))&&(!maxPrice||p.price<=Number(maxPrice))&&p.rating>=minRating});if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);if(sort==='newest')list.sort((a,b)=>Number(b.id)-Number(a.id));if(sort==='featured')list.sort((a,b)=>b.rating-a.rating||Number(a.id)-Number(b.id));return list}
function renderFilters(){const box=$('#filterCategories');if(!box)return;const counts={all:PRODUCTS.length};PRODUCTS.forEach(p=>counts[p.cat]=(counts[p.cat]||0)+1);box.innerHTML=[['all','الكل'],...['قطع غيار','زيوت','كهربائيات','إكسسوارات','أدوات'].map(x=>[x,x])].map(([v,l])=>`<button class="${activeCat===v?'active':''}" data-filter-cat="${esc(v)}">${esc(l)} <span>${num(counts[v]||0)}</span></button>`).join('')}
function renderActiveFilters(){const box=$('#activeFilters');if(!box)return;const parts=[];if(activeCat!=='all')parts.push(['الفئة',activeCat,'cat']);if(query)parts.push(['بحث',query,'query']);if(minPrice||maxPrice)parts.push(['السعر',`${minPrice||0} - ${maxPrice||'∞'}`,'price']);if(minRating)parts.push(['تقييم',`${minRating}+`,'rating']);box.innerHTML=parts.map(([l,v,k])=>`<span class="active-filter">${esc(l)}: ${esc(v)} <button data-remove-filter="${k}">×</button></span>`).join('')}
function productCard(p,i){return `<article class="product" data-product="${p.id}" style="animation-delay:${Math.min(i,9)*35}ms"><div class="product-img">${img(p)}<span class="badge">${esc(p.badge)}</span><button class="fav ${favs.includes(String(p.id))?'active':''}" data-fav="${p.id}" aria-label="المفضلة">${favs.includes(String(p.id))?'♥':'♡'}</button></div><div class="product-body"><div class="product-cat">${esc(p.cat)} · ${esc(p.brand)}</div><h3>${esc(p.name)}</h3><div class="meta-row"><div class="stars">★★★★★ <span>(${p.rating})</span></div><div class="stock ${p.stock<10?'low':''}">${p.stock<10?`متبقي ${num(p.stock)}`:'متوفر'}</div></div><div class="price-row"><span class="price">${money(p.price)}</span><span class="old">${money(p.old)}</span></div><button class="add" data-add="${p.id}">أضف للسلة</button></div></article>`}
function renderProducts(){const grid=$('#productGrid');if(!grid)return;const list=filterList(),shown=list.slice(0,visibleLimit);query=$('#searchInput')?.value.trim()||query;grid.innerHTML=shown.length?shown.map(productCard).join(''):'<div class="empty" style="grid-column:1/-1"><b>ما لقينا منتجات مطابقة</b><span>غيّر البحث أو الفلاتر حتى نعرض خيارات أكثر.</span></div>';$('#resultsText').textContent=`${num(list.length)} منتج متاح حالياً للطلب` ;$('#productCountLabel').textContent=list.length>visibleLimit?`يظهر ${num(shown.length)} من ${num(list.length)}`:`${num(list.length)} منتج`;$('#loadMoreWrap').style.display=list.length>visibleLimit?'block':'none';renderFilters();renderActiveFilters()}
function renderCart(){const count=$('#cartCount'),total=$('#cartTotal'),items=$('#cartItems');if(!count||!items)return;const qtyCount=cart.reduce((n,x)=>n+x.qty,0);count.textContent=num(qtyCount);total.textContent=money(subtotal());$('#cartSubtext').textContent=`${num(qtyCount)} ${qtyCount===1?'منتج':'منتجات'}`;items.innerHTML=cart.length?cart.map((x,i)=>{const p=get(x.id);return p?`<div class="cart-row" style="animation-delay:${i*35}ms"><div class="cart-thumb">${img(p,'cart-image')}</div><div><h4>${esc(p.name)}</h4><small>${money(p.price)}</small><div class="qty"><button data-minus="${p.id}">−</button><b class="latin">${num(x.qty)}</b><button data-plus="${p.id}">+</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`:''}).join(''):'<div class="empty"><b>السلة فارغة</b><span>أضف المنتجات وتابع الطلب.</span></div>'}
function openCart(){document.body.classList.add('drawer-open');$('#cartDrawer')?.classList.add('open');$('#overlay')?.classList.add('open')}
function closeCart(){document.body.classList.remove('drawer-open');$('#cartDrawer')?.classList.remove('open');if(!$('#modal')?.classList.contains('open'))$('#overlay')?.classList.remove('open')}
function add(id){const p=get(id);if(!p||p.stock<1)return toast('المنتج غير متوفر حالياً',false);const x=cart.find(i=>String(i.id)===String(p.id));if(x)x.qty=Math.min(x.qty+1,p.stock);else cart.push({id:p.id,qty:1});persist();renderCart();const el=document.querySelector(`.product[data-product="${p.id}"]`);el?.classList.add('flash');setTimeout(()=>el?.classList.remove('flash'),600);$('#cartBtn')?.classList.remove('bump');void $('#cartBtn')?.offsetWidth;$('#cartBtn')?.classList.add('bump');toast(`تمت إضافة ${p.name} للسلة`);openCart()}
function qty(id,d){const x=cart.find(i=>String(i.id)===String(id));if(!x)return;x.qty+=d;const p=get(id);if(p)x.qty=Math.min(x.qty,p.stock);if(x.qty<1)cart=cart.filter(i=>String(i.id)!==String(id));persist();renderCart()}
function modal(html){const box=$('#modalContent'),m=$('#modal');if(!box||!m)return;box.innerHTML=html;m.classList.add('open');document.body.classList.add('modal-open');$('#overlay')?.classList.add('open')}
function closeModal(){document.body.classList.remove('modal-open');$('#modal')?.classList.remove('open');if(!$('#cartDrawer')?.classList.contains('open'))$('#overlay')?.classList.remove('open')}
function filterCategory(c){activeCat=c;visibleLimit=9;renderProducts();$$('.main-nav a[data-cat],.category-card').forEach(x=>x.classList.toggle('active',x.dataset.cat===c));$('#shop')?.scrollIntoView({behavior:'smooth'});$('#categories')?.classList.remove('open')}
function toggleFav(id){id=String(id);favs=favs.includes(id)?favs.filter(x=>x!==id):[...favs,id];persist();renderProducts();toast(favs.includes(id)?'تمت الإضافة إلى المفضلة':'تمت الإزالة من المفضلة')}
function favorites(){const ps=favs.map(get).filter(Boolean);modal(`<button class="close-modal" data-close-modal>×</button><span class="eyebrow eyebrow-dark">SAVED</span><h2>المفضلة</h2>${ps.length?`<div class="mini-list">${ps.map(p=>`<button data-fav-add="${p.id}">${img(p,'mini-image')}<span>${esc(p.name)}</span><b>${money(p.price)}</b></button>`).join('')}</div>`:'<div class="empty"><b>المفضلة فارغة</b><span>اضغط القلب على أي منتج.</span></div>'}`)}
function showOrders(){modal(`<button class="close-modal" data-close-modal>×</button><span class="eyebrow eyebrow-dark">ORDERS</span><h2>طلباتي</h2>${orders.length?orders.map(o=>`<div class="order-card"><b>${esc(o.no)}</b><span>${esc(o.status)}</span><strong>${money(o.total)}</strong><small>${new Date(o.date).toLocaleDateString('en-GB')}</small></div>`).join(''):'<div class="empty">لا توجد طلبات بعد.</div>'}`)}
function track(){modal(`<button class="close-modal" data-close-modal>×</button><span class="eyebrow eyebrow-dark">TRACKING</span><h2>تتبع الطلب</h2><form class="checkout-form" id="trackForm"><input id="trackNo" placeholder="CAR-12345678" required><button class="btn btn-primary full">بحث</button></form><div id="trackResult"></div>`);$('#trackForm').onsubmit=e=>{e.preventDefault();const o=orders.find(x=>x.no===$('#trackNo').value.trim());$('#trackResult').innerHTML=o?`<div class="order-card"><b>${esc(o.no)}</b><span>${esc(o.status)}</span><strong>${money(o.total)}</strong><small>${new Date(o.date).toLocaleDateString('en-GB')}</small></div>`:'<div class="empty"><b>ما لقينا الطلب</b><span>تأكد من رقم الطلب.</span></div>'}}
function productDetails(id){const p=get(id);if(!p)return;if(!viewed.includes(String(id)))viewed=[String(id),...viewed].slice(0,5);persist();modal(`<button class="close-modal" data-close-modal>×</button><div class="detail-photo">${img(p,'detail-image')}</div><span class="eyebrow eyebrow-dark">${esc(p.cat)} · ${esc(p.sub)} · ${esc(p.brand)}</span><h2>${esc(p.name)}</h2><div class="stars">★★★★★ <span>(${p.rating})</span></div><div class="detail-price">${money(p.price)}</div><p class="muted">منتج متوفر ضمن كتالوج مركز السيارة مع سعر ومخزون واضحين ومعلومات توافق أساسية.</p><div class="fit-result">المخزون الحالي: <b class="latin">${num(p.stock)}</b> قطعة · التوافق: <b>${p.fit.map(esc).join('، ')}</b></div><div class="detail-actions"><button class="btn btn-primary" data-modal-add="${p.id}">أضف للسلة</button><button class="btn" data-modal-fav="${p.id}">${favs.includes(String(p.id))?'♥ محفوظة':'♡ المفضلة'}</button></div>`)}
function fitment(){modal(`<button class="close-modal" data-close-modal>×</button><span class="eyebrow eyebrow-dark">FITMENT</span><h2>اختيار حسب السيارة</h2><p class="muted">حدد الماركة ونوع القطعة حتى نضيّق النتائج.</p><form class="checkout-form" id="fitForm"><div class="form-row"><select id="fitMake" required><option value="">الماركة</option><option>Toyota</option><option>Hyundai</option><option>Kia</option><option>Nissan</option></select><input id="fitModel" required placeholder="الموديل"></div><div class="form-row"><input id="fitYear" type="number" min="1980" max="2035" inputmode="numeric" placeholder="Year"><select id="fitCat" required><option value="">نوع القطعة</option>${['قطع غيار','زيوت','إكسسوارات','كهربائيات','أدوات'].map(x=>`<option>${x}</option>`).join('')}</select></div><button class="btn btn-primary full">عرض النتائج</button></form>`);$('#fitForm').onsubmit=e=>{e.preventDefault();const make=$('#fitMake').value;activeCat=$('#fitCat').value;query=make;visibleLimit=9;closeModal();$('#searchInput').value='';renderProducts();activeCat=activeCat;$('#shop').scrollIntoView({behavior:'smooth'});toast(`عرض منتجات ${$('#fitCat').value} المناسبة لـ ${make}`)}}
function checkout(){if(!cart.length)return modal('<button class="close-modal" data-close-modal>×</button><h2>السلة فارغة</h2>');const sub=subtotal();modal(`<button class="close-modal" data-close-modal>×</button><span class="eyebrow eyebrow-dark">CHECKOUT</span><h2>إتمام الطلب</h2><div class="order-summary"><span>المنتجات</span><b>${money(sub)}</b></div><form class="checkout-form" id="orderForm"><div class="form-row"><input id="nm" required placeholder="الاسم الكامل"><input id="ph" required inputmode="tel" placeholder="07XXXXXXXXX"></div><div class="form-row"><select id="gov" required><option value="">المحافظة</option>${Object.keys(GOV).map(g=>`<option>${esc(g)}</option>`).join('')}</select><input id="area" required placeholder="المنطقة / القضاء"></div><textarea id="addr" rows="3" required placeholder="العنوان بالتفصيل وأقرب نقطة دالة"></textarea><select id="pay"><option>الدفع عند الاستلام</option><option>تحويل إلكتروني</option></select><div class="shipping-line"><span>الشحن</span><b id="sf">اختر المحافظة</b></div><div class="shipping-line total"><span>الإجمالي</span><b id="ft">${money(sub)}</b></div><button class="btn btn-primary full">تأكيد الطلب</button></form>`);$('#gov').onchange=()=>{const fee=Number(GOV[$('#gov').value]||0);$('#sf').textContent=money(fee);$('#ft').textContent=money(sub+fee)};$('#orderForm').onsubmit=e=>{e.preventDefault();const ph=$('#ph').value.replace(/\s/g,'');if(!/^07\d{9}$/.test(ph))return toast('رقم الهاتف يجب أن يبدأ بـ 07 ويتكون من 11 رقم',false);const shipping=Number(GOV[$('#gov').value]||0);const no=`CAR-${String(Date.now()).slice(-8)}`;orders.unshift({no,date:new Date().toISOString(),name:$('#nm').value,phone:ph,governorate:$('#gov').value,area:$('#area').value,address:$('#addr').value,payment:$('#pay').value,total:sub+shipping,status:'قيد المراجعة',items:[...cart]});cart=[];persist();renderCart();closeModal();modal(`<button class="close-modal" data-close-modal>×</button><div class="success"><div class="check">✓</div><h2>تم استلام طلبك</h2><p>رقم الطلب <b>${no}</b></p><button class="btn btn-primary" data-orders>عرض الطلب</button></div>`);toast('تم تسجيل الطلب بنجاح')}}
function info(title,text){modal(`<button class="close-modal" data-close-modal>×</button><span class="eyebrow eyebrow-dark">INFO</span><h2>${esc(title)}</h2><p class="info-text">${esc(text)}</p>`)}
function account(){modal(`<button class="close-modal" data-close-modal>×</button><span class="eyebrow eyebrow-dark">ACCOUNT</span><h2>حسابك</h2><p class="muted">التجربة الحالية تحفظ السلة والمفضلة والطلبات على جهازك. ربط الحسابات وسجل الطلبات السحابي يحتاج بيانات Supabase الحقيقية.</p><div class="detail-actions"><button class="btn btn-primary" data-orders>طلباتي</button><button class="btn" data-favorites>المفضلة</button></div>`)}
function searchSuggestions(){const box=$('#searchSuggestions'),input=$('#searchInput');if(!box||!input)return;const q=input.value.trim().toLowerCase();if(!q){box.classList.remove('open');return}const matches=PRODUCTS.filter(p=>`${p.name} ${p.brand} ${p.cat}`.toLowerCase().includes(q)).slice(0,5);box.innerHTML=matches.map(p=>`<button data-suggestion="${p.id}">${esc(p.name)} <small>· ${money(p.price)}</small></button>`).join('');box.classList.toggle('open',!!matches.length)}
function showViewed(){const dock=$('#quickViewDock');if(!dock)return;const ps=viewed.map(get).filter(Boolean).slice(0,2);dock.innerHTML=ps.length?ps.map(p=>`<div class="dock-card">${img(p)}<b>${esc(p.name)}</b><button data-dock-product="${p.id}">×</button></div>`).join(''):''}
function boot(){
  renderProducts();renderCart();showViewed();
  const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal').forEach(el=>obs.observe(el));
  window.addEventListener('scroll',()=>$('#siteHeader')?.classList.toggle('scrolled',scrollY>8),{passive:true});
  setTimeout(()=>$('#pageLoader')?.classList.add('hidden'),450);
  let counters=false;const cm=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!counters){counters=true;$$('[data-counter]').forEach(el=>{const target=Number(el.dataset.counter);let n=0;const steps=target<10?30:20;const timer=setInterval(()=>{n=Math.min(target,n+(target/steps));el.textContent=target%1?n.toFixed(1):Math.round(n);if(n>=target)clearInterval(timer)},35)});cm.disconnect()}}),{threshold:.5});const hero=document.querySelector('.hero');if(hero)cm.observe(hero);
}
document.addEventListener('click',e=>{
 const t=e.target.closest('button,a');if(!t)return;
 if(t.matches('[data-cat]')){e.preventDefault();filterCategory(t.dataset.cat);return}
 if(t.id==='mobileMenu'){e.preventDefault();$('#categories')?.classList.toggle('open');return}
 if(t.id==='cartBtn'){openCart();return}if(t.id==='closeCart'||t=== $('#overlay')){closeCart();closeModal();return}
 if(t.id==='accountBtn'||t.id==='footerAccount'){e.preventDefault();account();return}
 if(t.id==='favoritesHeader'||t.id==='favoritesLink'){e.preventDefault();favorites();return}
 if(t.id==='ordersLink'||t.id==='footerTrack'||t.id==='trackOrderLink'){e.preventDefault();track();return}
 if(t.id==='footerReturns'||t.id==='returnsLink'){e.preventDefault();info('الاستبدال والاسترجاع','يمكن طلب الاستبدال أو الاسترجاع للمنتج غير المطابق أو المتضرر وفق سياسة المتجر، مع توثيق حالة المنتج عند الاستلام.');return}
 if(t.id==='footerContact'||t.id==='contactLink'){e.preventDefault();info('تواصل معنا','للدعم والطلبات يمكنك استخدام رقم خدمة العملاء 0770 000 0000. سيتم ربط قنوات واتساب والبريد عند تجهيز بيانات المتجر النهائية.');return}
 if(t.id==='fitmentBtn'||t.id==='finderBtn'){fitment();return}
 if(t.id==='checkoutBtn'){checkout();return}
 if(t.id==='loadMore'){visibleLimit+=6;renderProducts();return}
 if(t.id==='resetFilters'){activeCat='all';query='';minPrice='';maxPrice='';minRating=0;visibleLimit=9;$('#searchInput').value='';$('#minPrice').value='';$('#maxPrice').value='';$$('#ratingFilters button').forEach(x=>x.classList.remove('active'));renderProducts();return}
 if(t.id==='applyFilters'){minPrice=$('#minPrice').value;maxPrice=$('#maxPrice').value;visibleLimit=9;$('#filterPanel').classList.remove('open');renderProducts();return}
 if(t.id==='filterToggle'){$('#filterPanel')?.classList.toggle('open');return}
 if(t.id==='searchBtn'){query=$('#searchInput').value.trim();visibleLimit=9;renderProducts();$('#shop').scrollIntoView({behavior:'smooth'});$('#searchSuggestions')?.classList.remove('open');return}
 if(t.id==='promoShop'){document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'});return}
 if(t.id==='closeCart'){closeCart();return}
 if(t.dataset.add){add(t.dataset.add);return}
 if(t.dataset.fav){e.stopPropagation();toggleFav(t.dataset.fav);return}
 if(t.dataset.plus){qty(t.dataset.plus,1);return}if(t.dataset.minus){qty(t.dataset.minus,-1);return}
 if(t.dataset.product){productDetails(t.dataset.product);return}
 if(t.dataset.closeModal){closeModal();return}
 if(t.dataset.modalAdd){add(t.dataset.modalAdd);closeModal();return}
 if(t.dataset.modalFav){toggleFav(t.dataset.modalFav);productDetails(t.dataset.modalFav);return}
 if(t.dataset.favAdd){add(t.dataset.favAdd);closeModal();return}
 if(t.dataset.orders){showOrders();return}if(t.dataset.favorites){favorites();return}
 if(t.dataset.dockProduct){productDetails(t.dataset.dockProduct);return}
 if(t.dataset.suggestion){const p=get(t.dataset.suggestion);if(p){$('#searchInput').value=p.name;query=p.name;renderProducts();$('#shop').scrollIntoView({behavior:'smooth'});$('#searchSuggestions').classList.remove('open')}return}
 if(t.dataset.removeFilter){const k=t.dataset.removeFilter;if(k==='cat')activeCat='all';if(k==='query'){query='';$('#searchInput').value=''}if(k==='price'){minPrice='';maxPrice='';$('#minPrice').value='';$('#maxPrice').value=''}if(k==='rating'){minRating=0;$$('#ratingFilters button').forEach(x=>x.classList.remove('active'))}renderProducts();return}
});
document.addEventListener('click',e=>{if(!e.target.closest('#heroSearchBox')&&!e.target.closest('#searchSuggestions'))$('#searchSuggestions')?.classList.remove('open')});
$('#sortSelect')?.addEventListener('change',e=>{sort=e.target.value;visibleLimit=9;renderProducts()});
$('#searchInput')?.addEventListener('input',e=>{query=e.target.value.trim();visibleLimit=9;searchSuggestions();renderProducts()});
$('#minPrice')?.addEventListener('change',e=>{minPrice=e.target.value});$('#maxPrice')?.addEventListener('change',e=>{maxPrice=e.target.value});
$('#ratingFilters')?.addEventListener('click',e=>{const b=e.target.closest('button[data-rating]');if(!b)return;minRating=Number(b.dataset.rating);$$('#ratingFilters button').forEach(x=>x.classList.toggle('active',x===b));visibleLimit=9;renderProducts()});
boot();